### PR TITLE
repo: create `labels.yml`

### PR DESCRIPTION
**Pull request by Autoparallel**
This PR adds a `labels.yml` file to our `.github` directory which will sync labels from there (though it may not delete old labels, which we may have to do manually). I got these labels from https://github.com/autoparallel/learner

### CODE REVIEW

**Comment by Autoparallel** [comment]
A note for the Pluto gang -- I prefer having labels synced like this. We should consider it on all our repos and template them moving forward :)

**Comment by Autoparallel** [comment]
Before merging, we should add any of the ronkathon specific labels we already have in here and want to keep.

A good example would be the "bounty" label.

**Review by 0xJepsen — APPROVED** [review]
I like these I can't think of any on the top of my head that are missing here.

**Comment by Autoparallel** [comment]
Don't merge yet -- I will merge when ready then.

Let me add some that we have that aren't currently in this yml

**Pull request merged**
