### PR TITLE
Feat/dsl

### PR DESCRIPTION
**Pull request by lonerapier**
This PR fixes/closes issue #53

Very rough right now, don't review.

### CODE REVIEW

**Comment by Autoparallel** [comment]
This is lookin' pretty good. Would love to work with you on this as it seems like a crucial part of this project.

**Comment by lonerapier** [comment]
Sure @Autoparallel, will connect with you. This is currently a straight port of plonkathon's [DSL compiler](https://github.com/0xPARC/plonkathon/tree/954c48f913febbd6d9acbee18a0586bfc0cefb03/compiler). Liked their approach a lot, so I didn't do any modifications yet. 

Right now, adding tests and documentation. Would love your help as there's significant work still pending here.

**Comment by lonerapier** [comment]
@Autoparallel @0xJepsen PR is mostly done, will rebase on #63 and add scalar field when it's merged. Would love your review on this.

**Comment by lonerapier** [comment]
@Autoparallel done

**Review by 0xJepsen — APPROVED** [review]
Im down to merge this in nice work!

**Comment by lonerapier** [comment]
added a README with a walkthrough on how DSL is parsed and required polynomials are created.

If @Autoparallel doesn't have any suggestions, I think, we can merge this

**Pull request merged**
